### ISSUE TITLE
Make top carousel fit to full page size

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/website-claud#9]
*Maybe look into moving it out of header or attach a `v-if="[something about $route object]"` property so carousel isn't visible on every page*

> if needed make a computed property that returns `this.$route.[something] === [something]`, try `console.log(this.$route)` to see what properties you'll have but you can use this to check if you're on the homepage to show carousel or something

- to make fullwidth add a class (best: `app__carousel`) to the carousel here: https://github.com/holistic-web/website-claud/blob/06b3cce3656384ce3a27424a270b1222798211f3/src/App.vue#L3

- then add styling for that class by adding ```.app__carousel{  
width: 100%,
...  }```
to https://github.com/holistic-web/website-claud/blob/06b3cce3656384ce3a27424a270b1222798211f3/src/App.vue#L78 (outside of `#app` selector)

**Comment by michaelfitzhavey** [comment]
- [ ] somewhere is setting `margin-top: 10px` on the carousel which is pushing it down off the route (somehow it's applying to three elements or something and so causing 30px drop. To look at what I'm talking about inspect the element.

**Comment by andrewlew1s** [comment]
Removed margin top, was in Carousel component. 
console-log returns no-console error, tried to fix from stackoverflow. Didn't work, lmk

**Comment by michaelfitzhavey** [comment]
stop committing on development plz

**Comment by michaelfitzhavey** [comment]
I've implemented most of the fixes, the link above may be useful anyway since I explain why etc and how the stuff works.

I've tidied things up a bit: #13 

And re: hiding / showing the carousel, I recommend making the script part of the [home page](https://github.com/holistic-web/website-claud/blob/development/src/containers/Home/Detail.vue) something like this:
```
export default {
	components: {
		Carousel
	},
	created() {
		console.log(this.$route);
	}
};
```

and seeing where that that leaves you
